using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PremKaushal.Models;

namespace PremKaushal.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ViewResult iMessage(FormCollection form)
        {
            PremKaushalEntities PEntity = new PremKaushalEntities();
            string name, msg, email, contact;
            name = form["fname"].Trim().ToString() + " " + form["lname"].Trim().ToString();
            msg = form["message"].Trim().ToString();
            email = form["email"].Trim().ToString();
            contact = form["phone"].Trim().ToString();
            try
            {
                PEntity.sp_insertMessage(name, msg, email, contact);
                string body = null;
                body = "<p>" + msg + "</p><hr/><h3>Thank You for contacting us.</h3>";
                Mail.sendInfo(email,"Your message sent succesfully", body);
                Mail.sendAlert("Alert: Message generated by "+ name +"<"+email+"><"+contact+">", body);
            }
            catch (Exception ex)
            {
                PEntity.sp_insertLog("Error", "Error inserting Message: " + ex.Message + ", " + ex.InnerException + ", " + ex.StackTrace);
            }
            PEntity.sp_insertLog("Info", "Message Inserted: " + name + ", " + msg + ", " + email);
            return View();
        }
    }
}
